services:
  - type: web
    name: zurdir-frontend
    env: node
    plan: starter
    build:
      cache:
        paths:
          - .next/cache
          - node_modules
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://zurdir-backend.onrender.com # Explicit URL
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
      - key: SENTRY_ORG
        value: darkmdcode
      - key: SENTRY_PROJECT
        value: zurdir

  - type: web
    name: zurdir-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zurdir-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        length: 64
      - key: ENCRYPTION_KEY
        generateValue: true
        length: 32

databases:
  - name: zurdir-db
    plan: starter
    ipAllowList: 
      - zurdir-frontend
      - zurdir-backend